spring: 
  profiles: 
    active: prod
    
name: cloud-config-base
---
spring: 
  profiles: dev
  application: 
    name: myconfig-dev

---
spring: 
  profiles: prod
  application: 
    name: myconfig-prod